### ISSUE TITLE
Full support of the symbolic utility test

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#65] opened 2019-01-29 13:26 UTC
Including the concrete parts about string comparison.

There is now in Morsmall a parser for the arguments of a `test` command: https://github.com/colis-anr/morsmall/blob/master/src/utilities/testParser.mli

@claudemarche Are you taking care of this?

**Comment by claudemarche** [comment] 2019-01-29 14:22
I'm going to take care of supporting option -d and -f first, then also -n and -z.
I will be happy to call your parser too. Thanks !

**Comment by benozol** [comment] 2019-02-01 16:04
Let’s make a list:
- `-e`: already there
- `-d`, `-f`: implemented by Claude in #67 (merged in master with f139540eef63c18c6bd4e8001dfb712557bcee51)
- …

**Comment by Niols** [comment] 2019-02-04 10:38
Oh, interesting. That's an issue in the conversion. I'll take care of it right away.

**Comment by claudemarche** [comment] 2019-02-04 10:41
Apparently caused by commit 23e594877f
How could you have pushed that commit on master? the tests fail!

**Comment by Niols** [comment] 2019-02-04 10:42
Err. Actually, I can't reproduce this neither on `master` nor on `extend_support_for_test`

**Comment by Niols** [comment] 2019-02-04 10:43
Is Morsmall up to date on your machine? The CI is happy with the aforementioned commit but one needs the last version of Morsmall. If it is pinned, opam update & upgrade should do the trick

**Comment by claudemarche** [comment] 2019-02-04 10:44
Oh I see, you updated morsmall in the meantime.
That means we have a very fragile build process here: I should have been warned that I have to update morsmall

**Comment by Niols** [comment] 2019-02-04 10:49
Yes, I had to in order to fix a bug. But indeed, since colis-language relies on Morsmall's ASTs, any change here can break everything. I wonder how we could improve that. The same will happen if we start using Morbig's dev version

**Comment by Niols** [comment] 2019-02-04 10:54
By the way, one can see here that `=`, `-x` and `-a` are pretty important:
http://ginette.informatique.univ-paris-diderot.fr/~niols/colis-covering-report/#execution-error

**Comment by claudemarche** [comment] 2019-02-04 10:55
Any new version of morsmall should have a new version number, and the build process should check that version number. I can't see any other way.
I don't know how you can check version number using dune, but it is probably possible.

**Comment by claudemarche** [comment] 2019-02-04 11:00
Thanks for the new diagram !
Question: I see 3 'Error' on the last column, but when I click on the "Error" word is goes to a place where only 2 "verification error" are listed. Is there a mistake in the counting ?

**Comment by claudemarche** [comment] 2019-02-04 11:01
"=" and "-x" are easy to do. For "-a" it is not so obvious... we could discuss on Wednesday

**Comment by Niols** [comment] 2019-02-04 12:39
http://ginette.informatique.univ-paris-diderot.fr/~niols/colis-covering-report/

17%!

But the results have to be mitigated: quite often, we manage to execute scripts that start with something like `if [ "$1" = configure ]; then`. Since this is false, we don't enter the if and don't fail if there are unsupported things in it.

I don't know what we should do with that. Run the symbolic engine several times with the different values that `$1` can have?

**Comment by benozol** [comment] 2019-02-04 13:10
Nice!

Given the limited number of values that `$1` can take, I’d also go for running the SE several times. (The alternative, symbolic variables in CoLiS would be a bit heavy…)

**Comment by claudemarche** [comment] 2019-02-05 13:36
What are those different values? Could we at least set the value to the one is used when installing a package?

**Comment by Niols** [comment] 2019-02-05 13:39
Err.. I don't quite remember. I'd have to dive into dpkg's documentation.

**Comment by claudemarche** [comment] 2019-02-05 13:39
What is the easier way for me to get a copy of the script corpus? Ideally, on a page like [this one](http://ginette.informatique.univ-paris-diderot.fr/~niols/colis-covering-report/group-412152964.html) I'd like to click on script names to see their contents

**Comment by Niols** [comment] 2019-02-05 16:39
You can find the script corpora on the colis git on gforge. Or you can click on script names and see their contents!

**Comment by Niols** [comment] 2019-02-05 16:39
> You can find the script corpora on the colis git on gforge. Or you can click on script names and see their contents!

C'est nouveau, ça vient de sortir.

**Comment by claudemarche** [comment] 2019-02-05 17:19
Tres joli ! Good job !

**Comment by Niols** [comment] 2019-02-06 11:18
> Err.. I don't quite remember. I'd have to dive into dpkg's documentation.

https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#summary-of-ways-maintainer-scripts-are-called

**Closed** 2020-02-21 12:35 UTC
